### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Zomis** [janosgyerik/hiring-tools#1]
Although this is not code, it is still.... stuff. Add a license to the project to make it clear who is allowed to use it and how. See also http://opensource.stackexchange.com/a/1721

**Comment by janosgyerik** [comment]
Good point. And I could really use help choosing a license. If you
recommend something, for example in a pull request, I'll probably just
agree right away and take it.

**Comment by Zomis** [comment]
Looks like you created one two days after your last comment :)
